In [1]:
import numpy as np

In [ ]:
l = [i for i in range(10)]

In [ ]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(l)

list

In [ ]:
array = np.array(l)

In [ ]:
type(array)

numpy.ndarray

In [ ]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
two_array = [
    [1,2],[3,5]
]

In [ ]:
two_array

[[1, 2], [3, 5]]

In [ ]:
array.shape

(10,)

In [ ]:
two_array

[[1, 2], [3, 5]]

In [ ]:
two_array.shape

(2,)

In [ ]:
two_array = np.array(two_array)

In [ ]:
two_array

array([2, 2])

In [ ]:
two_array.shape

(2,)

In [ ]:
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
array.dtype

dtype('int64')

In [ ]:
array.dtype=float

In [ ]:
array

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323,
       3.0e-323, 3.5e-323, 4.0e-323, 4.4e-323])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(10,dtype=np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(20,dtype=np.float)

<ipython-input-38-9841986ab32a>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.arange(20,dtype=np.float)


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
print(np.__version__)

1.22.4


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr = np.array((1,2,3,4,5))

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(np.__version__)

NameError: ignored

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.identity((2))

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.empty(())

array(1.)

In [ ]:
np.arange((10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])


In [ ]:
a.shape

(2, 3)

In [ ]:
a.ndim

2

In [ ]:
a.size

6

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = np.array([1,2,3],dtype=float)

In [ ]:
a

array([1., 2., 3.])

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])


[3 8]


In [ ]:
np.sort([2,5,1,8,9,6,7])

array([1, 2, 5, 6, 7, 8, 9])

In [11]:
np.argsort([23,23,1245])

array([0, 1, 2])

In [ ]:
A = np.array([1, 2, 3])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C=A+B

In [ ]:
C

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
a = np.add([1,2,3],[1,2,3])

In [ ]:
a

array([2, 4, 6])

In [ ]:
np.sine(34)

AttributeError: ignored

In [ ]:
np.sum([1,2,3,5,4])

15

In [8]:
np.min([2,5,7,3,9])

2

In [9]:
np.max([23,45,67,12])

67

In [10]:
np.mean([12,34,56,12])

28.5

In [12]:
np.argsort([23,67,1,89])

array([2, 0, 1, 3])

In [13]:
np.std([23,34,56,76])

20.41292482717751

In [2]:
np.sin(23)

-0.8462204041751706

In [3]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [4]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [9]:
arr = np.array([41,42,43,44])

fltr_arr = arr > 42

new_fltr_arr = arr[fltr_arr]

print(fltr_arr)
print(new_fltr_arr)


[False False  True  True]
[43 44]


In [7]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
